apiVersion: batch/v1
kind: Job
metadata:
  name: kuber-job
  namespace: app
spec:
  template:
    spec:
      containers:
        - name: migration
          image: tselofan/migration
          command: ["dotnet"]
          args: ["migration.dll", "migrate-database"]
          env:
            - name: db_connection_string
              valueFrom:
                secretKeyRef:
                  name: kuber-secret
                  key: db_connection_string
      restartPolicy: OnFailure