apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "homework-miniapi.fullname" . }}-{{ .Release.Revision }}
spec:
  ingressClassName: nginx
  rules:  
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /health
            pathType: Prefix
            backend:
              service:
                name: {{ include "homework-miniapi.fullname" . }}-{{ .Release.Revision }}
                port:
                  number: 80
          - path: /users
            pathType: Prefix
            backend:
              service:
                name: {{ include "homework-miniapi.fullname" . }}-{{ .Release.Revision }}
                port:
                  number: 80