apiVersion: v1
kind: Service
metadata:
  name: {{ include "homework-miniapi.fullname" . }}-{{ .Release.Revision }}
  labels:
    env: prod
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    env: prod
